apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.20-alpine
        volumeMounts:
        - name: my-properties
          mountPath: /etc/config
      volumes:
      - configMap:
          name: my-properties
        name: my-properties
